version: 7
profiles: []
groups: []
configSync:
  parts: {}
hotkeys:
  toggle-window:
    - Ctrl-Space
  copy-current-path: []
  ctrl-c:
    - Ctrl-C
  copy:
    - Ctrl-Shift-C
  paste:
    - Ctrl-Shift-V
    - Shift-Insert
  select-all:
    - Ctrl-Shift-A
  clear: []
  zoom-in:
    - Ctrl-=
    - Ctrl-Shift-=
  zoom-out:
    - Ctrl--
    - Ctrl-Shift--
  reset-zoom:
    - Ctrl-0
  home:
    - Home
  end:
    - End
  previous-word:
    - Ctrl-Left
  next-word:
    - Ctrl-Right
  delete-previous-word:
    - Ctrl-Backspace
  delete-line:
    - Ctrl-Shift-Backspace
  delete-next-word:
    - Ctrl-Delete
  search:
    - Ctrl-Shift-F
  pane-focus-all:
    - Ctrl-Shift-I
  focus-all-tabs:
    - Ctrl-Alt-Shift-I
  scroll-to-top:
    - Ctrl-PageUp
  scroll-up:
    - Alt-PageUp
  scroll-down:
    - Alt-PageDown
  scroll-to-bottom:
    - Ctrl-PageDown
  restart-telnet-session: []
  restart-ssh-session: []
  launch-winscp: []
  settings-tab: {}
  settings:
    - Ctrl-Shift-/
  serial:
    - Ctrl-Alt-K
  restart-serial-session: []
  new-tab:
    - Ctrl-Shift-T
  new-window:
    - Ctrl-Shift-N
  profile: {}
  profile-selectors: {}
  toggle-fullscreen:
    - F11
    - Alt-Enter
  close-tab:
    - Ctrl-Shift-W
  reopen-tab:
    - Ctrl-Shift-Z
  toggle-last-tab: []
  rename-tab:
    - Ctrl-Shift-R
  next-tab:
    - Ctrl-Shift-Right
    - Ctrl-Tab
    - Ctrl-Win-.
  move-tab-left:
    - Ctrl-Shift-PageUp
    - Ctrl-Shift-,
  move-tab-right:
    - Ctrl-Shift-PageDown
    - Ctrl-Shift-.
  rearrange-panes:
    - Ctrl-Shift
  duplicate-tab: []
  restart-tab: []
  reconnect-tab: []
  disconnect-tab: []
  explode-tab: []
  combine-tabs: []
  tab-1:
    - Alt-1
  tab-2:
    - Alt-2
  tab-3:
    - Alt-3
  tab-4:
    - Alt-4
  tab-5:
    - Alt-5
  tab-6:
    - Alt-6
  tab-7:
    - Alt-7
  tab-8:
    - Alt-8
  tab-9:
    - Alt-9
  tab-10:
    - Alt-0
  tab-11: []
  tab-12: []
  tab-13: []
  tab-14: []
  tab-15: []
  tab-16: []
  tab-17: []
  tab-18: []
  tab-19: []
  tab-20: []
  split-right:
    - Alt-R
  split-bottom:
    - Alt-D
  split-left: []
  split-top: []
  pane-nav-right:
    - Ctrl-Alt-Right
    - Alt-L
    - Alt-Right
  pane-nav-down:
    - Ctrl-Alt-Down
    - Alt-K
    - Alt-Down
  pane-nav-up:
    - Ctrl-Alt-Up
    - Alt-I
    - Alt-Up
  pane-nav-left:
    - Ctrl-Alt-Left
    - Alt-J
    - Alt-Left
  pane-nav-previous:
    - Ctrl-Alt-[
  pane-nav-next:
    - Ctrl-Alt-]
  pane-nav-1: []
  pane-nav-2: []
  pane-nav-3: []
  pane-nav-4: []
  pane-nav-5: []
  pane-nav-6: []
  pane-nav-7: []
  pane-nav-8: []
  pane-nav-9: []
  pane-maximize:
    - Ctrl-Alt-Enter
    - Ctrl-Shift-X
    - Alt-X
  close-pane: []
  pane-increase-vertical: []
  pane-decrease-vertical: []
  pane-increase-horizontal: []
  pane-decrease-horizontal: []
  switch-profile:
    - Ctrl-Alt-T
  profile-selector:
    - Ctrl-Shift-E
  command-selector:
    - Ctrl-Shift-P
  previous-tab:
    - Ctrl-Shift-Left
    - Ctrl-Shift-Tab
    - Ctrl-,
terminal:
  searchOptions: {}
  colorScheme:
    name: DotGov custom
    foreground: '#ebebeb'
    background: '#222a38'
    cursor: '#d73c38'
    colors:
      - '#222A38'
      - '#d73c38'
      - '#3cec85'
      - '#ffca28'
      - '#69c3ff'
      - '#7830b0'
      - '#8bd2ed'
      - '#ffffff'
      - '#222A38'
      - '#bf091d'
      - '#3d9751'
      - '#ffab00'
      - '#17b2e0'
      - '#7830b0'
      - '#8bd2ed'
      - '#ffffff'
  profile: local:wsl-Ubuntu-2404
  fontSize: 12
  cursor: beam
  font: FiraCode Nerd Font Mono Light
  lightColorScheme:
    name: Tabby Default Light
    foreground: '#4d4d4c'
    background: '#ffffff'
    cursor: '#4d4d4c'
    colors:
      - '#000000'
      - '#c82829'
      - '#718c00'
      - '#eab700'
      - '#4271ae'
      - '#8959a8'
      - '#3e999f'
      - '#ffffff'
      - '#000000'
      - '#c82829'
      - '#718c00'
      - '#eab700'
      - '#4271ae'
      - '#8959a8'
      - '#3e999f'
      - '#ffffff'
  customColorSchemes:
    - name: DotGov custom
      foreground: '#ebebeb'
      background: '#222a38'
      cursor: '#d73c38'
      colors:
        - '#222A38'
        - '#d73c38'
        - '#3cec85'
        - '#ffca28'
        - '#69c3ff'
        - '#7830b0'
        - '#8bd2ed'
        - '#ffffff'
        - '#222A38'
        - '#bf091d'
        - '#3d9751'
        - '#ffab00'
        - '#17b2e0'
        - '#7830b0'
        - '#8bd2ed'
        - '#ffffff'
ssh: {}
clickableLinks: {}
accessibility: {}
appearance: {}
hacks: {}
providerBlacklist: []
commandBlacklist: []
enableWelcomeTab: false
pluginBlacklist: []
profileDefaults:
  ssh:
    disableDynamicTitle: true
profileBlacklist: []
